Happy New Year Commit :D Only (ONLY \!\!\!) for test, don't use it version for releases, please. Otherwise you will not be able to avoid punishment by me :D
Returned SlidingMenu (but sliding with action bar don't working)
Begin rewrite Other block of demo (now not working)
Fastscroll for ListView (not tested)
Choice mode modal for GridView
And GridFragment (as ListFragment, but Grid)
Fix #256
Fix #253
Fix #250 (Activity.setUiOptions)
Fix #248
Close #249
Close #247 (TabWidget is deprecated for me, really)
Close #239 (Author not found)
Close #254 (Author not found?)
Close #233 (I was thinking: to hell)
Close #207 (I am a lazy bastard)
Close #262 (NoSuchMethodError: net.simonvt.widget.BuildLayerFrameLayout.setLayerType, try to find it :) )

Mmm... end of commit :D